# Generated by Django 3.1.1 on 2020-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='ques',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='userd',
            name='user',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userd',
            name='answer',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
