# Generated by Django 3.1.1 on 2020-09-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200930_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userd',
            name='answer',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
