# Generated by Django 3.1.1 on 2020-09-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200930_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userd',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.ques'),
            preserve_default=False,
        ),
    ]
