# Generated by Django 3.1.1 on 2020-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userd_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userd',
            name='answer',
            field=models.CharField(max_length=50),
        ),
    ]
